name: gh-pages-deploy
on: 
  push:
    branches:
       - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -e ./TuringPlugins
      - run: pip install -r requirements.txt
      - run: pip show mkdocs-material-extensions
      - run: mkdocs gh-deploy --force